name: update gamescope
on:
  schedule:
    # run every day at...
    - cron: "0 5 * * *"  # [5am UTC]/[6am UTC+1]
    - cron: "0 17 * * *" # [5pm UTC]/[6pm UTC+1]

  push:
    branches:
      - "update-gamescope-script"
      - "main"

jobs:
  check-for-new-commits:
    name: "Check for new commits Plagman/gamescope:master"
    runs-on: ubuntu-latest

    steps:
      - name: Set git
        run: |
          bot_id=$(
            curl --silent https://api.github.com/users/github-actions%5Bbot%5D \
            | grep '"id":'
          )
          bot_id="${bot_id//[!0-9]}"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "${bot_id}+github-actions[bot]@users.noreply.github.com"

      - name: Checkout gamescope-pkg repo with submodules
        uses: actions/checkout@v3
        with:
          ref: main
          submodules: recursive
          fetch-depth: 0

      - name: Save the current tag of submodule/gamescope
        run: |
          echo "CURRENT_TAG=$(git -C gamescope describe --tags HEAD)" >> $GITHUB_ENV

      - name: Pull and checkout master of Plagman/gamescope
        run: |
          git submodule update --remote gamescope

      - name: Get the new index of the current_tag of submodule/gamescope
        run: |
          hashes=$(git -C gamescope log --pretty='%H' ba4fbb3..HEAD)
          readarray -t TAGS < <(git -C gamescope describe --tags ${hashes})
          # exports array TAGS as a string TAGS_STRING
          # to import TAGS_STRING as the array TAGS in a following step:
          # readarray -d ' ' -t TAGS < <(echo "${{ env.TAGS_STRING }}")
          echo "TAGS_STRING=${TAGS[*]}" >> $GITHUB_ENV
          CURRENT_INDEX=0
          for t in "${TAGS[@]}"; do
            [[ "$t" == "${{ env.CURRENT_TAG }}" ]] && { echo "$CURRENT_INDEX"; break; }
            (( ++CURRENT_INDEX ))
          done
          echo "CURRENT_INDEX=$CURRENT_INDEX" >> $GITHUB_ENV
      - name: Install debchange without the bloated devscripts package
        run: |
          mkdir -p ${HOME}/.local/lib/perl/Devscripts
          mkdir -p ${HOME}/.local/bin
          echo "PERL5LIB=${HOME}/.local/lib/perl" >> $GITHUB_ENV
          curl -o ${HOME}/.local/lib/perl/Devscripts/Compression.pm \
            https://raw.githubusercontent.com/Debian/devscripts/master/lib/Devscripts/Compression.pm
          curl -o ${HOME}/.local/lib/perl/Devscripts/Debbugs.pm \
            https://raw.githubusercontent.com/Debian/devscripts/master/lib/Devscripts/Debbugs.pm
          curl -o ${HOME}/.local/bin/debchange \
            https://raw.githubusercontent.com/Debian/devscripts/master/scripts/debchange.pl
          chmod +x ${HOME}/.local/bin/debchange
      - name: Test if debchange funcional
        run: |
          env DEBFULLNAME='cloudishBenne' \
          DEBEMAIL='30512375+cloudishBenne@users.noreply.github.com' \
          debchange -h
